name: lua-busted-tests
run-name: ${{ github.actor }} running lua busted tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.1"
          - "5.2"
          - "5.3"
          - "luajit"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Lua Installation
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Luarocks Installation
        uses: leafo/gh-actions-luarocks@v4
      - name: Install Dependencies
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-reporter-lcov
      - name: Run busted tests
        run: |
          busted --coverage --output=utfTerminal
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          lcov-file: ./lcov.info
