name: lua-busted-tests
run-name: ${{ github.actor }} running lua busted tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.1"
          - "5.2"
          - "5.3"
          - "luajit"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Lua Installation
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Luarocks Installation
        uses: leafo/gh-actions-luarocks@v4
      - name: Install Dependencies
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-reporter-lcov
      - name: Run busted tests
        run: |
          busted --coverage --output=utfTerminal
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Code Coverage Report
        uses: zgosalvez/github-actions-report-lcov@v3.1.7
        with:
          coverage-files: ./lcov.info
          minimum-coverage: 88
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
